# Generated by Django 2.1 on 2019-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListGiay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GiayCode', models.CharField(max_length=20)),
                ('GiaySize', models.IntegerField(default=0)),
                ('GiayAnh', models.FileField(upload_to='./AnhGiay')),
                ('Borrow', models.CharField(max_length=1)),
                ('GiayStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('GiayNote', models.CharField(blank=True, max_length=100, null=True)),
                ('TimeBorrow', models.DateTimeField(verbose_name='Time borrows')),
                ('BorrowTimes', models.IntegerField(default=0)),
                ('TotalTimeUsing', models.DateTimeField(verbose_name='Used time')),
            ],
        ),
    ]
