# Generated by Django 2.1 on 2019-04-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_auto_20190406_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='listgiay',
            name='GiayName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
