# Generated by Django 2.1 on 2019-04-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_listgiay_giayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listgiay',
            name='GiayName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
